-- ============================================================================
-- schema.sql — AUTO-GENERATED from LIVE Supabase DB (Management API SQL).
-- Generated by gen_schema.py. Snapshot DDL: tables, columns, PK, UNIQUE, FK, RPC.
-- NOTE: indexes, RLS policies, triggers, enums, composite types are NOT fully
-- captured here — see supabase/migrations/ for full history. Use as reference only.
-- ============================================================================

CREATE TABLE public.accounts_payable (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_number text NOT NULL,
  supplier_name text NOT NULL,
  supplier_id uuid NULL,
  amount numeric NOT NULL,
  paid_amount numeric NULL DEFAULT 0,
  due_date date NOT NULL,
  status text NULL DEFAULT 'unpaid'::text,
  source text NOT NULL,
  source_id uuid NULL,
  notes text NULL,
  created_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT accounts_payable_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT accounts_payable_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.accounts_receivable (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_number text NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NULL,
  amount numeric NOT NULL,
  paid_amount numeric NULL DEFAULT 0,
  due_date date NOT NULL,
  status text NULL DEFAULT 'unpaid'::text,
  source text NOT NULL,
  source_id uuid NULL,
  notes text NULL,
  created_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT accounts_receivable_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_name text NOT NULL,
  record_id uuid NOT NULL,
  action text NOT NULL,
  old_data jsonb NULL,
  new_data jsonb NULL,
  changed_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT audit_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.chart_of_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL,
  name text NOT NULL,
  type text NOT NULL,
  parent_id uuid NULL,
  is_active boolean NULL DEFAULT true,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, c, o, d, e, }),
  CONSTRAINT chart_of_accounts_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.chart_of_accounts (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.custom_cake_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  req_number text NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  size text NOT NULL,
  flavor text NOT NULL,
  color_theme text NULL,
  special_notes text NULL,
  reference_image_url text NULL,
  quoted_price numeric NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, r, e, q, _, n, u, m, b, e, r, })
);

CREATE TABLE public.custom_cakes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  size text NOT NULL,
  shape text NOT NULL,
  flavor text NOT NULL,
  filling text NOT NULL,
  frosting text NOT NULL,
  fondant_color text NULL,
  message text NULL,
  special_request text NULL,
  reference_image_url text NULL,
  price numeric NULL DEFAULT 0,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, })
);

CREATE TABLE public.custom_product_addons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  name text NOT NULL,
  price integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT custom_product_addons_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.customer_order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  subtotal numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT customer_order_items_customer_order_id_fkey FOREIGN KEY (customer_order_id) REFERENCES public.customer_orders (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT customer_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.customer_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number text NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NULL,
  table_number text NULL,
  notes text NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  total_amount numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, o, r, d, e, r, _, n, u, m, b, e, r, })
);

CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NULL,
  customer_code text NOT NULL,
  name text NOT NULL,
  phone text NOT NULL,
  email text NULL,
  birth_date date NULL,
  gender text NULL,
  address text NULL,
  notes text NULL,
  tier user-defined NULL DEFAULT 'BRONZE'::customer_tier,
  points integer NULL DEFAULT 0,
  is_active boolean NULL DEFAULT true,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  total_spending numeric NOT NULL DEFAULT 0,
  total_orders integer NOT NULL DEFAULT 0,
  last_order_date timestamptz NULL,
  is_manual boolean NOT NULL DEFAULT false,
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, c, u, s, t, o, m, e, r, _, c, o, d, e, }),
  UNIQUE ({, p, h, o, n, e, }),
  CONSTRAINT customers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth.users (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category text NOT NULL,
  description text NOT NULL,
  amount numeric NOT NULL,
  expense_date date NOT NULL,
  receipt_url text NULL,
  created_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  status text NULL DEFAULT 'approved'::text,
  approved_by uuid NULL,
  approved_at timestamptz NULL,
  rejection_reason text NULL,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT expenses_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.fiscal_periods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  period_type text NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  is_closed boolean NULL DEFAULT false,
  closed_by uuid NULL,
  closed_at timestamptz NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, n, a, m, e, }),
  CONSTRAINT fiscal_periods_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.ingredient_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  name_en text NULL,
  description text NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, })
);

CREATE TABLE public.ingredients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NULL,
  name text NOT NULL,
  name_en text NULL,
  category_id uuid NULL,
  base_unit text NOT NULL,
  purchase_unit text NULL,
  conversion_rate numeric NULL DEFAULT 1,
  current_stock numeric NOT NULL DEFAULT 0,
  min_stock numeric NULL DEFAULT 0,
  max_stock numeric NULL,
  reorder_point numeric NULL,
  price_per_unit numeric NULL DEFAULT 0,
  last_purchase_price numeric NULL,
  average_price numeric NULL,
  shelf_life_days integer NULL,
  storage_location text NULL,
  preferred_supplier_id uuid NULL,
  is_active boolean NULL DEFAULT true,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  average_cost numeric NULL DEFAULT 0,
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, c, o, d, e, }),
  CONSTRAINT ingredients_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.ingredient_categories (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT ingredients_preferred_supplier_id_fkey FOREIGN KEY (preferred_supplier_id) REFERENCES public.suppliers (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.inventory_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_type text NOT NULL,
  item_id uuid NOT NULL,
  movement_type text NOT NULL,
  quantity numeric NOT NULL,
  unit text NOT NULL,
  stock_before numeric NOT NULL,
  stock_after numeric NOT NULL,
  unit_cost numeric NULL DEFAULT 0,
  total_cost numeric NULL DEFAULT 0,
  reference_type text NULL,
  reference_id uuid NULL,
  batch_code text NULL,
  expiry_date date NULL,
  reason text NULL,
  notes text NULL,
  created_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT inventory_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.journal_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entry_number text NOT NULL,
  entry_date date NOT NULL DEFAULT CURRENT_DATE,
  description text NOT NULL,
  source text NOT NULL,
  source_id uuid NULL,
  total_debit numeric NOT NULL DEFAULT 0,
  total_credit numeric NOT NULL DEFAULT 0,
  is_posted boolean NULL DEFAULT true,
  created_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, e, n, t, r, y, _, n, u, m, b, e, r, }),
  CONSTRAINT journal_entries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.journal_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entry_id uuid NOT NULL,
  account_id uuid NOT NULL,
  debit numeric NULL DEFAULT 0,
  credit numeric NULL DEFAULT 0,
  description text NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT journal_lines_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES public.journal_entries (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT journal_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.chart_of_accounts (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.loyalty_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NULL,
  order_id uuid NULL,
  points integer NOT NULL,
  transaction_type text NOT NULL,
  notes text NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT loyalty_transactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT loyalty_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE public.module_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  module text NOT NULL,
  can_view boolean NULL DEFAULT true,
  can_create boolean NULL DEFAULT false,
  can_edit boolean NULL DEFAULT false,
  can_delete boolean NULL DEFAULT false,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, u, s, e, r, _, i, d, ,, m, o, d, u, l, e, }),
  CONSTRAINT module_permissions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NULL,
  product_id uuid NULL,
  custom_cake_id uuid NULL,
  quantity integer NOT NULL DEFAULT 1,
  price numeric NULL DEFAULT 0,
  total numeric NULL DEFAULT 0,
  notes text NULL,
  created_at timestamptz NULL DEFAULT now(),
  product_name text NULL,
  unit_price numeric NULL DEFAULT 0,
  subtotal numeric NULL DEFAULT 0,
  variant_id uuid NULL,
  variant_name text NULL,
  addon_ids array NULL DEFAULT '{}'::uuid[],
  addon_detail jsonb NULL DEFAULT '[]'::jsonb,
  variant_price numeric NULL,
  addons jsonb NULL,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT order_items_custom_cake_id_fkey FOREIGN KEY (custom_cake_id) REFERENCES public.custom_cakes (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.order_status_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  old_status text NULL,
  new_status text NOT NULL,
  changed_by uuid NULL,
  note text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT order_status_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT order_status_logs_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.order_valid_transitions (
  from_status text NOT NULL,
  to_status text NOT NULL,
  PRIMARY KEY ({, f, r, o, m, _, s, t, a, t, u, s, ,, t, o, _, s, t, a, t, u, s, })
);

CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number text NOT NULL,
  customer_id uuid NULL,
  status user-defined NULL DEFAULT 'NEW'::order_status,
  payment_status user-defined NULL DEFAULT 'UNPAID'::payment_status,
  order_type user-defined NULL DEFAULT 'PICKUP'::order_type,
  pickup_date timestamptz NULL,
  delivery_date timestamptz NULL,
  delivery_address text NULL,
  subtotal numeric NULL DEFAULT 0,
  discount numeric NULL DEFAULT 0,
  tax numeric NULL DEFAULT 0,
  total numeric NULL DEFAULT 0,
  points_earned integer NULL DEFAULT 0,
  points_redeemed integer NULL DEFAULT 0,
  notes text NULL,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  customer_email text NULL,
  customer_address text NULL,
  pickup_time text NULL,
  payment_confirmed_at timestamptz NULL,
  payment_confirmed_by uuid NULL,
  confirmed_at timestamptz NULL,
  confirmed_by uuid NULL,
  customer_name text NULL,
  customer_phone text NULL,
  total_amount numeric NULL DEFAULT 0,
  discount_amount numeric NULL DEFAULT 0,
  payment_proof_url text NULL,
  sale_id uuid NULL,
  source text NULL DEFAULT 'portal'::text,
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, o, r, d, e, r, _, n, u, m, b, e, r, }),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers (id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT orders_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.payment_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ar_ap_type text NOT NULL,
  ar_ap_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_date date NOT NULL DEFAULT CURRENT_DATE,
  payment_method text NULL,
  notes text NULL,
  recorded_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT payment_records_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.price_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NULL,
  variant_id uuid NULL,
  old_price integer NOT NULL,
  new_price integer NOT NULL,
  changed_by uuid NULL,
  reason text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT price_history_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT price_history_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT price_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.product_addons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  name text NOT NULL,
  price integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT product_addons_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.product_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  name_en text NULL,
  emoji text NULL,
  description text NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, })
);

CREATE TABLE public.product_gallery (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  image_url text NOT NULL,
  caption text NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  variant_id uuid NULL,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT product_gallery_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT product_gallery_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.product_inventory (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NULL,
  batch_id uuid NULL,
  quantity integer NOT NULL,
  expiry_date date NULL,
  created_at timestamptz NULL DEFAULT now(),
  variant_id uuid NULL,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT product_inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT product_inventory_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.production_batches (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT product_inventory_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.product_option_groups (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  name text NOT NULL,
  display_type text NOT NULL DEFAULT 'radio'::text,
  sort_order integer NOT NULL DEFAULT 0,
  is_required boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT product_option_groups_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.product_option_values (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  group_id uuid NOT NULL,
  value text NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  image_url text NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT product_option_values_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.product_option_groups (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  order_id uuid NOT NULL,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  rating integer NOT NULL,
  comment text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  is_featured boolean NOT NULL DEFAULT false,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT product_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.product_tags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  emoji text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, n, a, m, e, })
);

CREATE TABLE public.product_tags_junction (
  product_id uuid NOT NULL,
  tag_id uuid NOT NULL,
  PRIMARY KEY ({, p, r, o, d, u, c, t, _, i, d, ,, t, a, g, _, i, d, }),
  CONSTRAINT product_tags_junction_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT product_tags_junction_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.product_tags (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.product_variants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  name text NOT NULL,
  price integer NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  option_text text NULL,
  image_url text NULL,
  recipe_url text NULL,
  cost_price numeric NOT NULL DEFAULT 0,
  stock integer NOT NULL DEFAULT 0,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.production_batches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  batch_number text NOT NULL,
  product_id uuid NULL,
  recipe_id uuid NULL,
  quantity_planned integer NOT NULL,
  quantity_produced integer NULL DEFAULT 0,
  quantity_defect integer NULL DEFAULT 0,
  status text NULL DEFAULT 'planned'::text,
  scheduled_date date NULL,
  started_at timestamptz NULL,
  completed_at timestamptz NULL,
  notes text NULL,
  created_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  cost_per_unit numeric NULL DEFAULT 0,
  total_cost numeric NULL DEFAULT 0,
  stock_consumed boolean NULL DEFAULT false,
  variant_id uuid NULL,
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, b, a, t, c, h, _, n, u, m, b, e, r, }),
  CONSTRAINT production_batches_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT production_batches_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT production_batches_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT production_batches_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  name_en text NULL,
  description text NULL,
  category text NULL,
  selling_price numeric NOT NULL,
  cost_price numeric NULL DEFAULT 0,
  image_url text NULL,
  is_active boolean NULL DEFAULT true,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  current_stock numeric NULL DEFAULT 0,
  min_stock numeric NULL DEFAULT 0,
  is_available_online boolean NULL DEFAULT false,
  online_description text NULL,
  online_sort_order integer NULL DEFAULT 0,
  category_id uuid NULL,
  is_featured boolean NOT NULL DEFAULT false,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL,
  role text NOT NULL,
  phone text NULL,
  avatar_url text NULL,
  is_active boolean NULL DEFAULT true,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES public.auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.push_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  endpoint text NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, u, s, e, r, _, i, d, ,, e, n, d, p, o, i, n, t, }),
  CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.recipe_ingredients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipe_id uuid NULL,
  ingredient_id uuid NULL,
  quantity numeric NOT NULL,
  unit text NOT NULL,
  notes text NULL,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT recipe_ingredients_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES public.recipes (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT recipe_ingredients_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.recipes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_id uuid NULL,
  yield_quantity integer NULL DEFAULT 1,
  instructions text NULL,
  prep_time_minutes integer NULL,
  bake_time_minutes integer NULL,
  bake_temperature integer NULL,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  variant_id uuid NULL,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT recipes_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT recipes_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE public.sale_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NULL,
  product_id uuid NULL,
  batch_id uuid NULL,
  product_name text NOT NULL,
  quantity integer NOT NULL,
  unit_price numeric NOT NULL,
  subtotal numeric NOT NULL,
  created_at timestamptz NULL DEFAULT now(),
  variant_name text NULL,
  variant_price numeric NULL,
  addons jsonb NULL,
  variant_id uuid NULL,
  addon_detail jsonb NULL DEFAULT '[]'::jsonb,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT sale_items_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.sales (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT sale_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT sale_items_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.production_batches (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT sale_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_number text NOT NULL,
  subtotal numeric NOT NULL,
  discount_amount numeric NULL DEFAULT 0,
  discount_percent numeric NULL DEFAULT 0,
  tax_amount numeric NULL DEFAULT 0,
  total numeric NOT NULL,
  payment_method text NULL,
  payment_amount numeric NULL,
  change_amount numeric NULL,
  customer_name text NULL,
  notes text NULL,
  status text NULL DEFAULT 'completed'::text,
  cashier_id uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  cogs numeric NULL DEFAULT 0,
  gross_profit numeric NULL DEFAULT 0,
  stock_deducted boolean NULL DEFAULT false,
  customer_phone text NULL,
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, i, n, v, o, i, c, e, _, n, u, m, b, e, r, }),
  CONSTRAINT sales_cashier_id_fkey FOREIGN KEY (cashier_id) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.stock_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ingredient_id uuid NULL,
  movement_type text NOT NULL,
  quantity numeric NOT NULL,
  unit text NOT NULL,
  stock_before numeric NOT NULL,
  stock_after numeric NOT NULL,
  reference_type text NULL,
  reference_id uuid NULL,
  batch_code text NULL,
  expiry_date date NULL,
  reason text NULL,
  notes text NULL,
  created_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT stock_movements_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT stock_movements_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.stock_opname_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  opname_id uuid NULL,
  ingredient_id uuid NULL,
  system_stock numeric NOT NULL,
  actual_stock numeric NULL,
  difference numeric NULL,
  unit text NOT NULL,
  reason text NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT stock_opname_items_opname_id_fkey FOREIGN KEY (opname_id) REFERENCES public.stock_opnames (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT stock_opname_items_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.stock_opnames (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  opname_number text NOT NULL,
  opname_date date NOT NULL,
  status text NULL DEFAULT 'draft'::text,
  notes text NULL,
  completed_at timestamptz NULL,
  created_by uuid NULL,
  approved_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  submitted_by uuid NULL,
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, o, p, n, a, m, e, _, n, u, m, b, e, r, }),
  CONSTRAINT stock_opnames_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT stock_opnames_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT stock_opnames_submitted_by_fkey FOREIGN KEY (submitted_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.stock_purchase_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_id uuid NULL,
  ingredient_id uuid NULL,
  quantity_ordered numeric NOT NULL,
  quantity_received numeric NULL DEFAULT 0,
  unit text NOT NULL,
  unit_price numeric NOT NULL,
  discount_percent numeric NULL DEFAULT 0,
  subtotal numeric NOT NULL,
  expiry_date date NULL,
  batch_code text NULL,
  created_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT stock_purchase_items_purchase_id_fkey FOREIGN KEY (purchase_id) REFERENCES public.stock_purchases (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT stock_purchase_items_ingredient_id_fkey FOREIGN KEY (ingredient_id) REFERENCES public.ingredients (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.stock_purchases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_number text NOT NULL,
  supplier_id uuid NULL,
  purchase_date date NOT NULL,
  received_date date NULL,
  subtotal numeric NULL DEFAULT 0,
  tax_amount numeric NULL DEFAULT 0,
  discount_amount numeric NULL DEFAULT 0,
  total_amount numeric NULL DEFAULT 0,
  payment_status text NULL DEFAULT 'unpaid'::text,
  payment_due_date date NULL,
  notes text NULL,
  invoice_number text NULL,
  status text NULL DEFAULT 'draft'::text,
  created_by uuid NULL,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  received_by uuid NULL,
  approved_by uuid NULL,
  approved_at timestamptz NULL,
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, p, u, r, c, h, a, s, e, _, n, u, m, b, e, r, }),
  CONSTRAINT stock_purchases_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT stock_purchases_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT stock_purchases_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT stock_purchases_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.store_settings (
  id bigint NOT NULL DEFAULT 1,
  company_name text NOT NULL DEFAULT 'Eattie Bakery'::text,
  short_name text NOT NULL DEFAULT 'Eattie'::text,
  tagline text NOT NULL DEFAULT 'Roti & Kue Segar, Dipesan, Dibuat, Diantar'::text,
  logo_url text NULL,
  logo_icon_url text NULL,
  favicon_url text NULL,
  primary_color text NOT NULL DEFAULT '32 95% 44%'::text,
  primary_color_hex text NOT NULL DEFAULT '#c87e1a'::text,
  accent_color text NOT NULL DEFAULT '38 55% 48%'::text,
  sidebar_color text NOT NULL DEFAULT '345 32% 18%'::text,
  whatsapp text NOT NULL DEFAULT ''::text,
  instagram text NOT NULL DEFAULT ''::text,
  facebook text NOT NULL DEFAULT ''::text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid NULL,
  email text NOT NULL DEFAULT ''::text,
  phone text NOT NULL DEFAULT ''::text,
  address text NOT NULL DEFAULT ''::text,
  currency_code text NOT NULL DEFAULT 'IDR'::text,
  locale text NOT NULL DEFAULT 'id-ID'::text,
  receipt_footer text NOT NULL DEFAULT 'Terima kasih telah berbelanja 🍞'::text,
  business_hours text NOT NULL DEFAULT '08:00 - 20:00'::text,
  features jsonb NOT NULL DEFAULT '{"qris": true, "loyalty": false, "custom_cake": true, "online_order": true}'::jsonb,
  background_color text NULL DEFAULT '35 35% 97%'::text,
  surface_color text NULL DEFAULT '0 0% 100%'::text,
  text_color text NULL DEFAULT '20 18% 14%'::text,
  text_muted_color text NULL DEFAULT '20 10% 50%'::text,
  border_color text NULL DEFAULT '30 15% 88%'::text,
  button_text_color text NULL DEFAULT '0 0% 100%'::text,
  success_color text NULL DEFAULT '145 45% 34%'::text,
  danger_color text NULL DEFAULT '355 68% 46%'::text,
  warning_color text NULL DEFAULT '38 82% 42%'::text,
  sidebar_text_color text NULL DEFAULT '35 20% 90%'::text,
  footer_bg_color text NULL DEFAULT '345 32% 18%'::text,
  footer_text_color text NULL DEFAULT '35 20% 90%'::text,
  text_secondary_color text NULL DEFAULT '20 12% 35%'::text,
  accent_foreground_color text NULL DEFAULT '0 0% 100%'::text,
  surface_raised_color text NULL DEFAULT '35 30% 99%'::text,
  accent_subtle_color text NOT NULL DEFAULT '38 60% 95%'::text,
  PRIMARY KEY ({, i, d, }),
  CONSTRAINT store_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_person text NULL,
  phone text NULL,
  email text NULL,
  address text NULL,
  notes text NULL,
  is_active boolean NULL DEFAULT true,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  PRIMARY KEY ({, i, d, })
);

CREATE TABLE public.variant_option_values (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  variant_id uuid NOT NULL,
  option_value_id uuid NOT NULL,
  PRIMARY KEY ({, i, d, }),
  UNIQUE ({, v, a, r, i, a, n, t, _, i, d, ,, o, p, t, i, o, n, _, v, a, l, u, e, _, i, d, }),
  CONSTRAINT variant_option_values_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES public.product_variants (id) ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT variant_option_values_option_value_id_fkey FOREIGN KEY (option_value_id) REFERENCES public.product_option_values (id) ON UPDATE CASCADE ON DELETE CASCADE
);


-- ============================================================================
-- FUNCTIONS (RPC)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.calculate_customer_tier(p_total_spending numeric)
RETURNS text
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY INVOKER;

CREATE OR REPLACE FUNCTION public.check_order_rate_limit(p_phone text)
RETURNS boolean
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.complete_production_batch(p_batch_id uuid, p_quantity_produced numeric, p_quantity_defect numeric DEFAULT 0)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.confirm_order(p_order_id uuid, p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.convert_base_unit(p_qty numeric, p_from text, p_to text)
RETURNS numeric
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY INVOKER;

CREATE OR REPLACE FUNCTION public.decrement_variant_stock(p_variant_id uuid, p_qty integer)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.fn_journalize_expense()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.fn_journalize_purchase()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.fn_journalize_sale()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.fn_update_overdue_status()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.generate_customer_code()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.generate_invoice_number()
RETURNS text
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.generate_order_number()
RETURNS text
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_recipe_id_for_product(p_product_id uuid, p_variant_id uuid DEFAULT NULL::uuid)
RETURNS uuid
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS text
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.handle_audit_log()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.has_module_access(p_module text, p_action text DEFAULT 'view'::text)
RETURNS boolean
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.log_order_status_change()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.next_doc_number(p_prefix text, p_table text, p_column text)
RETURNS text
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.process_purchase(p_purchase_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.process_sale(p_sale_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.process_stock_opname(p_opname_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.rpc_cancel_order(p_order_id uuid, p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.rpc_complete_order(p_order_id uuid, p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.rpc_confirm_order(p_order_id uuid, p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.rpc_deliver_order(p_order_id uuid, p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.rpc_mark_paid(p_order_id uuid, p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.rpc_ready_for_pickup(p_order_id uuid, p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.rpc_start_production(p_order_id uuid, p_user_id uuid)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.sync_order_total()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY INVOKER;

CREATE OR REPLACE FUNCTION public.touch_custom_cake_updated_at()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY INVOKER;

CREATE OR REPLACE FUNCTION public.touch_customer_updated_at()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY INVOKER;

CREATE OR REPLACE FUNCTION public.track_order(p_order_number text, p_phone text)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.trg_sync_customer_from_order()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.trg_sync_customer_from_sale()
RETURNS trigger
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.upsert_customer_from_transaction(p_name text, p_phone text, p_amount numeric, p_order_date timestamp with time zone)
RETURNS void
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.validate_order_transition(p_from text, p_to text)
RETURNS void
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY INVOKER;

CREATE OR REPLACE FUNCTION public.void_sale(p_sale_id uuid, p_user_id uuid, p_reason text DEFAULT NULL::text)
RETURNS jsonb
LANGUAGE plpgsql AS $$
-- body omitted (regenerate via pg_dump for full body); signature above is authoritative
$$ SECURITY DEFINER;
